### ISSUE TITLE
Purchaseable extra slots

### ISSUE THREAD

**Issue by Mystic-Ervo** [cmooref17/Lethal-Company-HotbarPlus#2]
In the same way that [reserved slots](https://github.com/cmooref17/ReservedItemSlotMods) can be purchased as an upgrade for the entire crew, I think it would be interesting to be able to configure extra inventory slots as an upgrade as well.

The host could set the price for new slots, as well as the maximum number of slots to purchase. An incremental price increase could also be implemented so that each slot costs more than the previous one.

**Comment by cmooref17** [comment]
I do want to do this, and it is on my TODO list, but I just haven't set out an amount of time to do it yet.
It honestly wouldn't be too bad if I copy alot of the code that I used with my ReservedItemSlot mods, but maybe I can get to it soon.

**Comment by Mystic-Ervo** [comment]
Recycling saves the planet, isn't it?
I can't wait to try it in-game

**Comment by Schurches** [comment]
I'm looking forward to this one too!

**Comment by cmooref17** [comment]
I actually just added this today! It might have some bugs, but I will be testing this more, and waiting for bug reports, so please create another issue if you run into any bugs related to this!
